<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MM5QJ97" name="risTestScripts.ReportPrintTest" tests="1" failures="1" timestamp="11 Feb 2022 06:22:24 GMT" time="32.324" errors="0">
  <testcase name="printReportMisTest" time="32.324" classname="risTestScripts.ReportPrintTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Failed: orderDate is incorrect in mis report page as:11/2/2022Expected orderDate:11/02/2022 expected [true] but found [false],
	Failed: scheduleDateTime is incorrect in mis report page as:11/2/2022 - 12:00 AMExpected scheduleDateTime:11/02/2022 12:00 AM expected [true] but found [false],
	Failed: MISReport Actual: Roon No Expected: Room No expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Failed: orderDate is incorrect in mis report page as:11/2/2022Expected orderDate:11/02/2022 expected [true] but found [false],
	Failed: scheduleDateTime is incorrect in mis report page as:11/2/2022 - 12:00 AMExpected scheduleDateTime:11/02/2022 12:00 AM expected [true] but found [false],
	Failed: MISReport Actual: Roon No Expected: Room No expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at risTestScripts.ReportPrintTest.printReportMisTest(ReportPrintTest.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- printReportMisTest -->
</testsuite> <!-- risTestScripts.ReportPrintTest -->
